/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterRouteImport } from './routes/waiter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTableIdRouteImport } from './routes/t.$tableId'
import { Route as ApiTablesRouteImport } from './routes/api/tables'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiMenuRouteImport } from './routes/api/menu'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiBillRouteImport } from './routes/api/bill'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth.me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'

const WaiterRoute = WaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableIdRoute = TTableIdRouteImport.update({
  id: '/t/$tableId',
  path: '/t/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTablesRoute = ApiTablesRouteImport.update({
  id: '/api/tables',
  path: '/api/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuRoute = ApiMenuRouteImport.update({
  id: '/api/menu',
  path: '/api/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillRoute = ApiBillRouteImport.update({
  id: '/api/bill',
  path: '/api/bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/waiter': typeof WaiterRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/bill': typeof ApiBillRoute
  '/api/events': typeof ApiEventsRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/tables': typeof ApiTablesRoute
  '/t/$tableId': typeof TTableIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/waiter': typeof WaiterRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/bill': typeof ApiBillRoute
  '/api/events': typeof ApiEventsRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/tables': typeof ApiTablesRoute
  '/t/$tableId': typeof TTableIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/waiter': typeof WaiterRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/bill': typeof ApiBillRoute
  '/api/events': typeof ApiEventsRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/tables': typeof ApiTablesRoute
  '/t/$tableId': typeof TTableIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/waiter'
    | '/api/admin'
    | '/api/bill'
    | '/api/events'
    | '/api/inventory'
    | '/api/menu'
    | '/api/orders'
    | '/api/sessions'
    | '/api/tables'
    | '/t/$tableId'
    | '/api/auth/login'
    | '/api/auth/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/waiter'
    | '/api/admin'
    | '/api/bill'
    | '/api/events'
    | '/api/inventory'
    | '/api/menu'
    | '/api/orders'
    | '/api/sessions'
    | '/api/tables'
    | '/t/$tableId'
    | '/api/auth/login'
    | '/api/auth/me'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/waiter'
    | '/api/admin'
    | '/api/bill'
    | '/api/events'
    | '/api/inventory'
    | '/api/menu'
    | '/api/orders'
    | '/api/sessions'
    | '/api/tables'
    | '/t/$tableId'
    | '/api/auth/login'
    | '/api/auth/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  WaiterRoute: typeof WaiterRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiBillRoute: typeof ApiBillRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiInventoryRoute: typeof ApiInventoryRoute
  ApiMenuRoute: typeof ApiMenuRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiTablesRoute: typeof ApiTablesRoute
  TTableIdRoute: typeof TTableIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter': {
      id: '/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableId': {
      id: '/t/$tableId'
      path: '/t/$tableId'
      fullPath: '/t/$tableId'
      preLoaderRoute: typeof TTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tables': {
      id: '/api/tables'
      path: '/api/tables'
      fullPath: '/api/tables'
      preLoaderRoute: typeof ApiTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu': {
      id: '/api/menu'
      path: '/api/menu'
      fullPath: '/api/menu'
      preLoaderRoute: typeof ApiMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bill': {
      id: '/api/bill'
      path: '/api/bill'
      fullPath: '/api/bill'
      preLoaderRoute: typeof ApiBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  WaiterRoute: WaiterRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiBillRoute: ApiBillRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiInventoryRoute: ApiInventoryRoute,
  ApiMenuRoute: ApiMenuRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiTablesRoute: ApiTablesRoute,
  TTableIdRoute: TTableIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
